#!/bin/bash

PATH_TO_AUTH_HOOK="/tmp/auth-hook.sh"
PATH_TO_CLEANUP_HOOK="/tmp/cleanup-hook.sh"

chmod +x "$PATH_TO_AUTH_HOOK"
chmod +x "$PATH_TO_CLEANUP_HOOK"

DOMAINS="-d your-domain -d *your-domain2"

sudo certbot certonly --manual \
  --preferred-challenges dns \
  --manual-auth-hook "$PATH_TO_AUTH_HOOK" \
  --manual-cleanup-hook "$PATH_TO_CLEANUP_HOOK" \
  $DOMAINS \
  --non-interactive \
  --agree-tos \
  --email your-email \
  --key-type ecdsa
